# Generated by Django 4.0.5 on 2022-07-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NewBookscategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OldBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=500)),
                ('book_price', models.IntegerField(default=1000)),
                ('book_description1', models.TextField()),
                ('book_description2', models.TextField()),
                ('book_description3', models.TextField()),
                ('book_seller_name', models.CharField(max_length=700)),
                ('book_seller_contact', models.IntegerField()),
                ('book_seller_info', models.TextField()),
                ('book_categoryname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingthings.newbookscategory')),
            ],
        ),
        migrations.CreateModel(
            name='NewBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=500)),
                ('book_price', models.IntegerField(default=1000)),
                ('available_stocks', models.IntegerField(default=10)),
                ('book_description1', models.TextField()),
                ('book_description2', models.TextField()),
                ('book_description3', models.TextField()),
                ('book_authorname', models.CharField(max_length=700)),
                ('book_categoryname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingthings.newbookscategory')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=400)),
                ('author_post', models.TextField()),
                ('published_date', models.DateField()),
                ('blog_title', models.TextField()),
                ('blog_description', models.TextField()),
                ('blog_description2', models.TextField()),
                ('blog_description3', models.TextField()),
                ('blog_image', models.ImageField(upload_to='media')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingthings.blogcategory')),
            ],
        ),
    ]
